services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: rental_db
      MYSQL_USER: rental_user
      MYSQL_PASSWORD: rental_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
